export const PRE_OVULATION = 'PRE_OVULATION';
export const OVULATION = 'OVULATION';
export const POST_OVULATION = 'POST_OVULATION';
export const APPEAR_OVULE = 'APPEAR_OVULE';
export const DISAPPEAR_OVULE = 'DISAPPEAR_OVULE';
export const DELETE_OVARIES = 'DELETE_OVARIES';
export const DELETE_PITUITARY = 'DELETE_PITUITARY';
